services:
  scooters:
    image: best-scooter/scooter-app
    volumes:
      - hardware:/scooter-app/model/hardware/:ro
    environment:
      - NODE_ENV=simulation
    deploy:
      mode: replicated
      replicas: 10

volumes:
  hardware:
